### PR TITLE
Small suggestion to update Max for input number for Battery Rated Capacity and Battery charge power 

### PR DESCRIPTION
**Pull request by heinoskov**
To new s7 series and to charge power to support 3x batteries (maybe this even should be higher)?

### CODE REVIEW

**Comment by Roving-Ronin** [comment]
Hi,

Issue with this is that the step is still in 5kWh increments, so you'll never be able to support setting the increments for both 5kWh and 7kWh modules. Also btw the LUNA S1 can be added in parallel up to 4 units in total, allowing for a maximum of 84kWh.

```
  battery_rated_capacity:
    name: "Battery Rated Capacity (in kWh)"
    min: 5
    max: 42
    step: 5
```

This setting also will vary depending upon LUNA S0 or S1 being installed, so easy for novices to make errors with, let alone the setting can be changed at whim. i.e. I have a user that sets there charge power ~3kW as this means the batteries don't heat up as much and typically equates to a longer lifespan from them.

```

  battery_charge_power:
    name: "Battery Charge Power"
    min: 0
    max: 10.5
    step: 0.01
```

These items, and addition of new inverter models and LUNA S1 are all something that needs to be addressed, but would really be best served by the release of WLCRS's 'next' release (i.e. v1.5.x ?). In that there's updated modbus registers that I added a few months ago that will allow automating a bunch of these inputs. (As well as including battery temperature support by default and also probably including support for the new Huawei EMMA device, that also replaces the traditional DDSU/DTSU meter).

Here's a screenshot from an install with 2 x L1 5kWh inverters and a 15kWh LUNA S0 running the newer code, and publishing some of these sensors:



NB: 'Inverters - Active Power Control' by default is named 'Inverter 1 - Active Power Control', but in a cascade of inverters it controls the overall power that all the inverters will produce and be allowed to export to the grid. i.e. In this case the owner has set it to limit exports to 4.7kW maximum (legal maximum for his DNSP is 5kW on a single phase setup).

**Comment by JensenNick** [comment]
Input about the battery is only used in the STAT package (it has no effect in the PEES package). I will spilt the input file so that we have one for PEES and one for STAT and add support for the S1 model (7/14/21 kWh modules) as well.

**Comment by heinoskov** [comment]
Thanks @Roving-Ronin for input which is valid. Guess i close this pull request?

**Comment by Roving-Ronin** [comment]
Above picture and comment (at bottom) updated/added, in my response above.

**Comment by heinoskov** [comment]
Nice! - when is next release set to go GA?

**Comment by Roving-Ronin** [comment]
Up to whenever WLCRS (Thijs) decides to release. I would guess he's waiting for feedback/testing on addition of support for Huawei EMMA though.

**Pull request closed without merging**
